version: "3.8"

services:
  app:
    image: ghcr.io/hueske-digital/systemstats:latest
    restart: unless-stopped
    environment:
      - HCLOUD_TOKEN
      - HCLOUD_SERVER_ID
    networks:
      proxy_apps:

networks:
  proxy_apps:
    name: proxy_apps
    external: true